meta_product_name: "Bucket List"
meta_title: "Bucket List - Don't waste time chasing your dreams."
meta_description: "Find the best deals on all the activities you love, without wasting time, because, we put them together for you"
meta_image: "share-image.jpg" # should exist in `app/assets/images/`